# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- script: |
    npm install
  workingDirectory: fujiji-client/
  displayName: 'Install packages'
- script: |
    npx chromatic --project-token=$(CHROMATIC_PROJECT_TOKEN)
  workingDirectory: fujiji-client/
  displayName: 'Publish storybook to Chromatic'
