# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    workingDirectory: fujiji-server/
    displayName: "npm install and build"
  - task: Docker@2
    inputs:
      containerRegistry: "fujijicontainer"
      repository: "Azure Container Registry"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile.prod"
      tags: $(Build.BuildNumber)
    displayName: "Docker image build"
