import Head from 'next/head';
import { Navigation, AdListing } from '../components';

export default function Home() {
  const props = {
    imageUrl: 'https://bit.ly/2Z4KKcF',
    imageAlt: 'Rear view of modern home with pool',
    beds: 3,
    baths: 2,
    title: 'Modern home in city center in the heart of historic Los Angeles',
    formattedPrice: '$1,900.00',
    reviewCount: 34,
    rating: 4,
  };
  return (
    <div>
      <Head>
        <title>Fujiji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation title="Fujiji" />
      <AdListing {...props} />
    </div>
  );
}
