import Head from 'next/head';
import { Navigation, AdListings } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fujiji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation title="Fujiji" />
      <AdListings data={['some changes', 'test2', 'test3']} />
    </div>
  );
}
