import Head from 'next/head';
import {
  Box,
  Flex,
  Stack,
  Heading,
  Link,
  Button,
  Image,
} from '@chakra-ui/react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fujiji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Box w="100%" h="80vh" bgGradient={['linear(to-b,white, teal.500)']}>
          <Flex
            align="center"
            justify={{ base: 'center', md: 'center', xl: 'center' }}
            direction={{ base: 'column-reverse', md: 'row' }}
            wrap="no-wrap"
            minH="70vh"
            px={8}
            mt={24}
          >
            <Stack direction={['column', 'row']} spacing="24px">
              <Box boxSize={['xxs', 'xs', 's']}>
                <Heading
                  as="h1"
                  size="xl"
                  fontWeight="bold"
                  color="primary.600"
                  textAlign={['center', 'center', 'left', 'left']}
                >
                  Ready to Explore the Furniture World?
                </Heading>
                <Box display="flex" alignItems="center">
                  <Link href="/search" pt={8} display="flex" mt="2" alignItems="center">
                    <Button
                      colorScheme="primary"
                      borderRadius="8px"
                      py="4"
                      px="4"
                      lineHeight="1"
                      size="md"
                      align={['center', 'center', 'left', 'left']}
                    >
                      Let&apos;s Search
                    </Button>
                  </Link>
                </Box>
              </Box>
              <Box boxSize={['xxs', 'xs', 'md']}>
                <Image
                  src="https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"
                  rounded="1rem"
                  shadow="2xl"
                />
              </Box>
            </Stack>
          </Flex>
        </Box>
      </div>
    </div>
  );
}
