version: "3"

services:
  fujiji-frontend-app:
    image: 'fujiji-client-image'
    container_name: 'fujiji-client'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    