version: '3'

services:
  fujiji-backend-app:
    image: 'fujiji-server-image'
    container_name: 'fujiji-server'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '8000:8000'

  fujiji-db:
     image: mcr.microsoft.com/mssql/server:2019-latest
     container_name: fujiji-db
     restart: always
     ports:
       - 1433:1433
     environment:
       MSSQL_SA_PASSWORD: 'Fujiji123'
       ACCEPT_EULA: 'Y'
     volumes:
       - ./migration-scripts:/scripts/