version: '3'

services:
  fujiji-backend-app:
    image: 'fujiji-server-image'
    container_name: 'fujiji-server'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '8000:8000'
