import PropTypes from 'prop-types';
import Head from 'next/head';
import { Box, Flex } from '@chakra-ui/react';
import Footer from '../Footer/Footer';
import NavBar from '../NavBar/NavBar';

export default function PageLayout({ children }) {
  return (
    <Flex
      direction="column"
      flexGrow="1"
      justifyContent="space-between"
      minH="100vh"
    >
      <Head>
        <title>Fujiji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <Box id="mainContainer" p="1">{children}</Box>
      </main>
      <Footer />
    </Flex>
  );
}

PageLayout.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node,
  ]).isRequired,
};
